name:
  value: admin
  
spring:
  cloud:
    config:
      override-system-properties: false

# Spring Boot Actuator + Micrometer Tracing 설정 영역
management:
  tracing:
    sampling:
      probability: 1.0